mysql:
  build: mysql
  ports:
    - 6603:3306
  restart: always
quick-loan-admin:
  build: quick-loan-admin-portal
  ports:
    - 8084:8089
  restart: always
speed-loan:
  build: speed-loan
  ports:
    - 8085:4200
  restart: always
quick-loan-service:
  build: quick-loan-services
  ports:
    - 8086:8080
  restart: always
uplportal:
  build: uplportal
  ports:
    - 8087:8088
  restart: always


